version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  python-api:
    image: gcr.io/lbg-python-cohort-8/gopal-python-api:latest
    build: ./