apiVersion: v1
kind: Service
metadata:
  name: python-api
spec:
  type: ClusterIP
  selector:
    app: python-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  labels:
    app: python-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python-api
  strategy:
    rollingUpdate:
      maxSurge: 10% 
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        imagePullPolicy: Always
        image: gcr.io/lbg-python-cohort-8/gopal-python-api:latest
        ports:
        - containerPort: 8080